# config.yml

app:
  debug_status: true

logger:
  error_log_path: "logs/error/error.log"
  sql_log_path: "logs/sql/sql.log"
  general_log_path: "logs/general/app.log"


server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "appuser"
  password: "secret"
  dbname: "appdb"
  sslmode: "disable"
  max_connections: 20
  max_idle_connections: 5

security:
  jwt_secret: "supersecretkey"
  token_expiry: 24h
  allowed_origins:
    - "https://app.example.com"
    - "https://admin.example.com"
